version: '3.8'

services:
  postgres:
    image: postgres:13-alpine
    environment:
      POSTGRES_USER: jivapay
      POSTGRES_PASSWORD: jivapay
      POSTGRES_DB: jivapay_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  redis:
    image: redis:6-alpine
    ports:
      - '6379:6379'

  merchant_api:
    build:
      context: .
      dockerfile: Dockerfile
    command: uvicorn backend.servers.merchant.server:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./backend:/app/backend
    environment:
      DATABASE_URL: postgresql://jivapay:jivapay@postgres:5432/jivapay_db
      REDIS_URL: redis://redis:6379/0
      S3_ENDPOINT_URL: http://minio:9000
      S3_ACCESS_KEY: minio
      S3_SECRET_KEY: minio123
      S3_BUCKET_NAME: jivapay
    ports:
      - '8001:8000'
    depends_on:
      - postgres
      - redis

  trader_api:
    build:
      context: .
      dockerfile: Dockerfile
    command: uvicorn backend.servers.trader.server:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./backend:/app/backend
    environment:
      DATABASE_URL: postgresql://jivapay:jivapay@postgres:5432/jivapay_db
      REDIS_URL: redis://redis:6379/0
    ports:
      - '8002:8000'
    depends_on:
      - postgres
      - redis

  gateway_api:
    build:
      context: .
      dockerfile: Dockerfile
    command: uvicorn backend.servers.gateway.server:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./backend:/app/backend
    environment:
      DATABASE_URL: postgresql://jivapay:jivapay@postgres:5432/jivapay_db
      REDIS_URL: redis://redis:6379/0
      S3_ENDPOINT_URL: http://minio:9000
      S3_ACCESS_KEY: minio
      S3_SECRET_KEY: minio123
      S3_BUCKET_NAME: jivapay
    ports:
      - '8003:8000'
    depends_on:
      - postgres
      - redis

  admin_api:
    build:
      context: .
      dockerfile: Dockerfile
    command: uvicorn backend.servers.admin.server:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./backend:/app/backend
    environment:
      DATABASE_URL: postgresql://jivapay:jivapay@postgres:5432/jivapay_db
    ports:
      - '8004:8000'
    depends_on:
      - postgres

  support_api:
    build:
      context: .
      dockerfile: Dockerfile
    command: uvicorn backend.servers.support.server:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./backend:/app/backend
    environment:
      DATABASE_URL: postgresql://jivapay:jivapay@postgres:5432/jivapay_db
    ports:
      - '8005:8000'
    depends_on:
      - postgres

  worker:
    build:
      context: .
      dockerfile: Dockerfile
    command: celery -A backend.worker.app worker --loglevel=info
    volumes:
      - ./backend:/app/backend
    environment:
      DATABASE_URL: postgresql://jivapay:jivapay@postgres:5432/jivapay_db
      REDIS_URL: redis://redis:6379/0
    depends_on:
      - postgres
      - redis

volumes:
  postgres_data: {} 