"""init

Revision ID: 968cc15566f6
Revises: 
Create Date: 2025-04-29 13:58:38.659189

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '968cc15566f6'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('super_admin', sa.Boolean(), nullable=True),
    sa.Column('access', sa.Boolean(), nullable=True),
    sa.Column('two_fa_code', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_admins_id'), 'admins', ['id'], unique=False)
    op.create_table('banks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bank_name', sa.String(length=100), nullable=False),
    sa.Column('public_name', sa.String(length=255), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('interbank', sa.Boolean(), nullable=False),
    sa.Column('access', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bank_name')
    )
    op.create_index(op.f('ix_banks_id'), 'banks', ['id'], unique=False)
    op.create_table('exchange_rates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('fiat', sa.String(length=10), nullable=False),
    sa.Column('buy_rate', sa.DECIMAL(precision=20, scale=8), nullable=False),
    sa.Column('sell_rate', sa.DECIMAL(precision=20, scale=8), nullable=False),
    sa.Column('median_rate', sa.DECIMAL(precision=20, scale=8), nullable=False),
    sa.Column('source', sa.String(length=255), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exchange_rates_id'), 'exchange_rates', ['id'], unique=False)
    op.create_table('fiat_currencies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('currency_name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('access', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('currency_name')
    )
    op.create_index(op.f('ix_fiat_currencies_id'), 'fiat_currencies', ['id'], unique=False)
    op.create_table('merchants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('two_factor_auth_token', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('access', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_merchants_id'), 'merchants', ['id'], unique=False)
    op.create_table('payment_methods',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('method_name', sa.String(length=50), nullable=False),
    sa.Column('public_name', sa.String(length=255), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('access', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('method_name')
    )
    op.create_index(op.f('ix_payment_methods_id'), 'payment_methods', ['id'], unique=False)
    op.create_table('supports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('access_to', sa.Text(), nullable=False),
    sa.Column('access', sa.Boolean(), nullable=True),
    sa.Column('two_fa_code', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_supports_id'), 'supports', ['id'], unique=False)
    op.create_table('time_zones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=False),
    sa.Column('utc_offset', sa.Integer(), nullable=False),
    sa.Column('access', sa.Boolean(), nullable=True),
    sa.Column('regions', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('avalible_bank_methods',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bank_id', sa.Integer(), nullable=False),
    sa.Column('method_id', sa.Integer(), nullable=False),
    sa.Column('access', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['bank_id'], ['banks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['method_id'], ['payment_methods.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_avalible_bank_methods_id'), 'avalible_bank_methods', ['id'], unique=False)
    op.create_table('merchant_stores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('merchant_id', sa.Integer(), nullable=False),
    sa.Column('store_name', sa.String(length=255), nullable=False),
    sa.Column('currency_id', sa.Integer(), nullable=False),
    sa.Column('balance', sa.DECIMAL(precision=20, scale=2), nullable=False),
    sa.Column('public_api_key', sa.String(length=255), nullable=False),
    sa.Column('private_api_key', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('trafic_access', sa.Boolean(), nullable=True),
    sa.Column('access', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['currency_id'], ['fiat_currencies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_merchant_stores_id'), 'merchant_stores', ['id'], unique=False)
    op.create_table('traders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('avatar_url', sa.String(length=255), nullable=True),
    sa.Column('currency_id', sa.Integer(), nullable=False),
    sa.Column('fiat_id', sa.Integer(), nullable=False),
    sa.Column('verification_level', sa.String(length=50), nullable=False),
    sa.Column('pay_in', sa.Boolean(), nullable=True),
    sa.Column('pay_out', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('trafic_priority', sa.Integer(), nullable=False),
    sa.Column('in_work', sa.Boolean(), nullable=True),
    sa.Column('trafic_access', sa.Boolean(), nullable=True),
    sa.Column('access', sa.Boolean(), nullable=True),
    sa.Column('two_factor_auth_token', sa.String(length=32), nullable=True),
    sa.Column('time_zone_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['currency_id'], ['fiat_currencies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['fiat_id'], ['fiat_currencies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['time_zone_id'], ['time_zones.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_traders_id'), 'traders', ['id'], unique=False)
    op.create_table('balance_stores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('currency_id', sa.Integer(), nullable=False),
    sa.Column('balance', sa.DECIMAL(precision=20, scale=2), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['currency_id'], ['fiat_currencies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['store_id'], ['merchant_stores.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_balance_stores_id'), 'balance_stores', ['id'], unique=False)
    op.create_table('balance_traders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trader_id', sa.Integer(), nullable=False),
    sa.Column('currency_id', sa.Integer(), nullable=False),
    sa.Column('balance', sa.DECIMAL(precision=20, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['currency_id'], ['fiat_currencies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['trader_id'], ['traders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_balance_traders_id'), 'balance_traders', ['id'], unique=False)
    op.create_table('balans_history_traders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trader_id', sa.Integer(), nullable=False),
    sa.Column('fiat_id', sa.Integer(), nullable=False),
    sa.Column('currency_id', sa.Integer(), nullable=False),
    sa.Column('operation_type', sa.String(length=50), nullable=False),
    sa.Column('network', sa.String(length=50), nullable=False),
    sa.Column('commission', sa.DECIMAL(precision=20, scale=2), nullable=False),
    sa.Column('amount', sa.DECIMAL(precision=20, scale=2), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['currency_id'], ['fiat_currencies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['fiat_id'], ['fiat_currencies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['trader_id'], ['traders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_balans_history_traders_id'), 'balans_history_traders', ['id'], unique=False)
    op.create_table('req_traders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trader_id', sa.Integer(), nullable=False),
    sa.Column('method_id', sa.Integer(), nullable=False),
    sa.Column('bank_id', sa.Integer(), nullable=False),
    sa.Column('req_number', sa.String(), nullable=False),
    sa.Column('fio', sa.String(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('lower_limit', sa.DECIMAL(precision=20, scale=2), nullable=False),
    sa.Column('upper_limit', sa.DECIMAL(precision=20, scale=2), nullable=False),
    sa.Column('total_limit', sa.DECIMAL(precision=20, scale=2), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['bank_id'], ['banks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['method_id'], ['payment_methods.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['trader_id'], ['traders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_req_traders_id'), 'req_traders', ['id'], unique=False)
    op.create_table('store_addresses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('merchant_id', sa.Integer(), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=False),
    sa.Column('currency_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['currency_id'], ['fiat_currencies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['store_id'], ['merchant_stores.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_store_addresses_id'), 'store_addresses', ['id'], unique=False)
    op.create_table('store_gateways',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['store_id'], ['merchant_stores.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_store_gateways_id'), 'store_gateways', ['id'], unique=False)
    op.create_table('trader_addresses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trader_id', sa.Integer(), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=False),
    sa.Column('currency_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['currency_id'], ['fiat_currencies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['trader_id'], ['traders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trader_addresses_id'), 'trader_addresses', ['id'], unique=False)
    op.create_table('work_balans_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trader_id', sa.Integer(), nullable=False),
    sa.Column('fiat_id', sa.Integer(), nullable=False),
    sa.Column('currency_id', sa.Integer(), nullable=False),
    sa.Column('exchange_rate', sa.DECIMAL(precision=20, scale=8), nullable=False),
    sa.Column('operation_type', sa.String(length=50), nullable=False),
    sa.Column('amount_currency', sa.DECIMAL(precision=20, scale=8), nullable=False),
    sa.Column('amount_fiat', sa.DECIMAL(precision=20, scale=2), nullable=False),
    sa.Column('commission', sa.DECIMAL(precision=20, scale=2), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['currency_id'], ['fiat_currencies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['fiat_id'], ['fiat_currencies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['trader_id'], ['traders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_work_balans_history_id'), 'work_balans_history', ['id'], unique=False)
    op.create_table('avalible_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('request_id', sa.Integer(), nullable=False),
    sa.Column('bank_id', sa.Integer(), nullable=False),
    sa.Column('method_id', sa.Integer(), nullable=False),
    sa.Column('upper_limit', sa.DECIMAL(precision=20, scale=2), nullable=False),
    sa.Column('lower_limit', sa.DECIMAL(precision=20, scale=2), nullable=False),
    sa.Column('total_limit', sa.DECIMAL(precision=20, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['bank_id'], ['banks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['method_id'], ['payment_methods.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['request_id'], ['req_traders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_avalible_requests_id'), 'avalible_requests', ['id'], unique=False)
    op.create_table('order_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hash_id', sa.String(length=255), nullable=False),
    sa.Column('trader_id', sa.Integer(), nullable=False),
    sa.Column('merchant_id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('requeset_id', sa.Integer(), nullable=False),
    sa.Column('method_id', sa.Integer(), nullable=False),
    sa.Column('bank_id', sa.Integer(), nullable=False),
    sa.Column('currency_id', sa.Integer(), nullable=False),
    sa.Column('fiat_id', sa.Integer(), nullable=False),
    sa.Column('order_type', sa.String(length=50), nullable=False),
    sa.Column('exchange_rate', sa.DECIMAL(precision=20, scale=8), nullable=False),
    sa.Column('amount_currency', sa.DECIMAL(precision=20, scale=8), nullable=False),
    sa.Column('total_fiat', sa.DECIMAL(precision=20, scale=2), nullable=False),
    sa.Column('merchant_commission', sa.DECIMAL(precision=20, scale=2), nullable=False),
    sa.Column('trader_commission', sa.DECIMAL(precision=20, scale=2), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['bank_id'], ['banks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['currency_id'], ['fiat_currencies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['fiat_id'], ['fiat_currencies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['method_id'], ['payment_methods.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['requeset_id'], ['req_traders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['store_id'], ['merchant_stores.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['trader_id'], ['traders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_history_id'), 'order_history', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_order_history_id'), table_name='order_history')
    op.drop_table('order_history')
    op.drop_index(op.f('ix_avalible_requests_id'), table_name='avalible_requests')
    op.drop_table('avalible_requests')
    op.drop_index(op.f('ix_work_balans_history_id'), table_name='work_balans_history')
    op.drop_table('work_balans_history')
    op.drop_index(op.f('ix_trader_addresses_id'), table_name='trader_addresses')
    op.drop_table('trader_addresses')
    op.drop_index(op.f('ix_store_gateways_id'), table_name='store_gateways')
    op.drop_table('store_gateways')
    op.drop_index(op.f('ix_store_addresses_id'), table_name='store_addresses')
    op.drop_table('store_addresses')
    op.drop_index(op.f('ix_req_traders_id'), table_name='req_traders')
    op.drop_table('req_traders')
    op.drop_index(op.f('ix_balans_history_traders_id'), table_name='balans_history_traders')
    op.drop_table('balans_history_traders')
    op.drop_index(op.f('ix_balance_traders_id'), table_name='balance_traders')
    op.drop_table('balance_traders')
    op.drop_index(op.f('ix_balance_stores_id'), table_name='balance_stores')
    op.drop_table('balance_stores')
    op.drop_index(op.f('ix_traders_id'), table_name='traders')
    op.drop_table('traders')
    op.drop_index(op.f('ix_merchant_stores_id'), table_name='merchant_stores')
    op.drop_table('merchant_stores')
    op.drop_index(op.f('ix_avalible_bank_methods_id'), table_name='avalible_bank_methods')
    op.drop_table('avalible_bank_methods')
    op.drop_table('time_zones')
    op.drop_index(op.f('ix_supports_id'), table_name='supports')
    op.drop_table('supports')
    op.drop_index(op.f('ix_payment_methods_id'), table_name='payment_methods')
    op.drop_table('payment_methods')
    op.drop_index(op.f('ix_merchants_id'), table_name='merchants')
    op.drop_table('merchants')
    op.drop_index(op.f('ix_fiat_currencies_id'), table_name='fiat_currencies')
    op.drop_table('fiat_currencies')
    op.drop_index(op.f('ix_exchange_rates_id'), table_name='exchange_rates')
    op.drop_table('exchange_rates')
    op.drop_index(op.f('ix_banks_id'), table_name='banks')
    op.drop_table('banks')
    op.drop_index(op.f('ix_admins_id'), table_name='admins')
    op.drop_table('admins')
    # ### end Alembic commands ###
